### ISSUE TITLE
Origins enderman death message doesn't translate

### ISSUE THREAD

**Issue by lochnessdragon** [arthurbambou/Fabric---Discord-Link#136] opened 2021-02-24 01:19 UTC
**Describe the bug**
When an enderian dies in water, the bot outputs death.attack.hurt_by_water instead of <player> took a bath for too long.

**Reproduction steps**

1. Install Origins on a server
2. Install Fabric--Discord-Link
3. Play as an enderian and jump in water
4. Wait till you die
5. Look in the discord chat

**Expected behaviour**
Instead of death.attack.hurt_by_water there should be <player> took a bath for too long.

**Additional context**

- Minecraft version: 1.16.5
- Fabric-Discord Link version: 0.8.9

- :exclamation: A list of all mods you were using:
    - Dynmap
    - Fabric Api
    - Fabric Discord Link
    - Hydrogen
    - Lithium
    - LuckPerms
    - Origins
    - Phosphor
    - WorldEdit

**fdlink.json**
Please attach your configuration file (`fdlink.json`) here (edit the token out)
```
{
  "chatChannels": [
    "<token>"
  ],
  "logChannels": [
    "<token>"
  ],
  "webhookURL": "",
  "ignoreBots": true,
  "activityUpdateInterval": 120,
  "minecraftToDiscord": {
    "general": {
      "enableDebugLogs": false
    },
    "chatChannels": {
      "commandPrefix": "-",
      "allowDiscordCommands": true,
      "serverStartingMessage": true,
      "serverStartMessage": true,
      "serverStopMessage": true,
      "serverStoppingMessage": true,
      "customChannelDescription": false,
      "minecraftToDiscordTag": false,
      "minecraftToDiscordDiscriminator": false,
      "playerMessages": true,
      "teamPlayerMessages": true,
      "joinAndLeaveMessages": true,
      "advancementMessages": true,
      "challengeMessages": true,
      "goalMessages": true,
      "deathMessages": true,
      "sendMeCommand": true,
      "sendSayCommand": true,
      "adminMessages": false,
      "atATellRaw": false,
      "achievementMessages": true
    },
    "logChannels": {
      "serverStartingMessage": true,
      "serverStartMessage": true,
      "serverStopMessage": true,
      "serverStoppingMessage": true,
      "customChannelDescription": false,
      "minecraftToDiscordTag": false,
      "minecraftToDiscordDiscriminator": false,
      "playerMessages": false,
      "teamPlayerMessages": false,
      "joinAndLeaveMessages": true,
      "advancementMessages": false,
      "challengeMessages": false,
      "goalMessages": false,
      "deathMessages": true,
      "sendMeCommand": true,
      "sendSayCommand": true,
      "adminMessages": true,
      "atATellRaw": false,
      "achievementMessages": true
    }
  },
  "discordToMinecraft": {
    "pingLongVersion": false
  },
  "emojiMap": [
    {
      "name": "example_name",
      "id": ":example_id:22222222"
    },
    {
      "name": "example_name2",
      "id": ":example_id2:22222222"
    }
  ],
  "version": 8,
  "token": "<token>"
}
```

**Comment by thecatcore** [comment] 2021-08-14 13:15
Duplicate of #164

**Closed as completed by thecatcore** 2021-08-14 13:15 UTC
Labels: bug, compatibility
