### ISSUE TITLE
\ character causes this log

### ISSUE THREAD

**Issue by Droon99-Developer** [arthurbambou/Fabric---Discord-Link#87] opened 2020-07-15 13:55 UTC
When the `\` character is typed into discord, the server crashes with this log:
```05:17:04] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Matcher.java:809) ~[?:1.8.0_242]
	at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_242]
	at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_242]
	at fr.arthurbambou.fdlink.discordstuff.DiscordBot.lambda$new$5(DiscordBot.java:139) ~[FDLink-0.4.2.jar:?]
	at net.fabricmc.fabric.impl.event.lifecycle.LegacyEventInvokers.lambda$onInitialize$2(LegacyEventInvokers.java:33) ~[0eebcb02-f9cf-452b-a698-e96e177dea57.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zzp000$onEndTick(MinecraftServer.java:1735) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:855) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]```

**Comment by trunkyredstone** [comment] 2020-07-16 08:15
Please check existing issues first. This is a duplicate of #83

**Closed as completed** 2020-07-16 12:51 UTC
