### ISSUE TITLE
Class casting exception

### ISSUE THREAD

**Issue by trunkyredstone** [arthurbambou/Fabric---Discord-Link#79] opened 2020-06-29 11:32 UTC
I got this exception with no apparent cause, similar to issue #77 

ERROR: net.minecraft.class_2585 cannot be cast to net.minecraft.class_2588 

The server then stops.

**Comment by thecatcore** [comment] 2020-06-29 15:33
duplicate of #77

**Closed as completed by thecatcore** 2020-06-29 15:33 UTC
