### ISSUE TITLE
tellraw @a messages not being sent to Discord

### ISSUE THREAD

**Issue by LessThanBenji** [arthurbambou/Fabric---Discord-Link#115] opened 2020-11-12 09:49 UTC
Hi, I'm using Fabric-Discord Link v0.7.16 on the latest build of Fabric for 1.16.3. Everything is working fine, apart from tellraw @a messages, which aren't being sent to Discord. I have the atATellRaw option set to true in fdlink.json and I haven't touched the atATellRaw option in messages.json (it's still set to "%messages"). I have a few datapacks in my world that use functions to send messages to all players using /tellraw @a <message> (no sub-selectors, just straight-up "@a") but none of these messages are appearing in Discord. All other messages (join/leave messages, player messages, death messages, advancement messages, admin commands, etc.) are being sent to Discord perfectly fine. The only mods I have installed alongside Fabric-Discord Link are Lithium, Phosphor, Carpet (with two extensions), and obviously the Fabric API, none of which should affect Fabric-Discord Link in any way. Any idea what the problem could be? Thanks for your help :)

**Comment by FalseMSP** [comment] 2020-12-07 01:04
Same here, if you find/found out how to do it reply to this thread.

**Comment by LessThanBenji** [comment] 2020-12-07 12:15
I haven't found a solution yet, unfortunately.

**Comment by thecatcore** [comment] 2021-01-20 09:19
I can't reproduce the issue, does it still occur?

**Comment by FalseMSP** [comment] 2021-01-22 23:18
Yes i believe so.. haven't checked in a while though... The problem is that tellraw commands don't get sent to the discord thingy.

**Closed as completed** 2021-04-03 20:33 UTC
Labels: bug
