### ISSUE TITLE
Player messages not showing

### ISSUE THREAD

**Issue by GlitchyIsTrash** [arthurbambou/Fabric---Discord-Link#148] opened 2021-05-24 18:26 UTC
Messages are showing up in the minecraft chat when typing in the discord channel but not showing in the discord channel when typing from the minecraft chat (/say works but not talking normaly)

- Minecraft version: 1.16.5
- Fabric-Discord Link version: 0.9.0
- mods: on image
- config: only changed ```
"chatChannels"
 "logChannels"
 "token"
```
(can't link the json github doesn't let me)

**Comment by GlitchyIsTrash** [comment] 2021-05-24 18:27
![image_2021-05-24_202714](https://user-images.githubusercontent.com/54434871/119391257-6cd33d00-bcce-11eb-873c-67ae50bc4203.png)

**Comment by Redo11** [comment] 2021-06-30 00:29
I got the same problem
![image](https://user-images.githubusercontent.com/49594490/123884176-f23fb200-d94a-11eb-8e35-e65df473af3b.png)
from discord it works perfectly fine, not the other way around

**Comment by thecatcore** [comment] 2021-08-14 13:09
Duplicate of #158

**Closed as completed by thecatcore** 2021-08-14 13:09 UTC
Labels: bug
