### ISSUE TITLE
player join messeage is not sended

### ISSUE THREAD

**Issue by wb1016** [arthurbambou/Fabric---Discord-Link#154] opened 2021-06-16 16:13 UTC
### **Describe the bug**
player join messeage, which you can enable by setting `"joinAndLeaveMessages": true` is not sended to discord.
this bug appeared after i updated mod and server to 1.17.

### **Reproduction steps**
1. set up 1.16.5 server and mod
2. update server and crash it by not updating mod
3. update mod
4. boom

### enviroment
- AdoptOpenJDK16
- Windows x86_64

### mod file list
- fabric-api-0.35.1+1.17.jar
- Fabric-Discord-Link-0.9.4.jar
- fastfurnace-1.17-3.0.jar
- image2map-0.2.0.jar
- jline4mcdsrv-0.2.0.jar
- lazydfu-0.1.2.jar
- leafmealone-2.1.jar
- lithium-fabric-mc1.17-0.7.0.jar
- minimotd-fabric-mc1.17-2.0.3-SNAPSHOT+e50953c.jar
- modupdater-1.1.11+21w08b.jar
- pingspam-1.2.0-1.17.jar
- PlayerPig-1.0.jar
- styled-chat-1.0.0.jar

### fdlink.json
```
  "chatChannels": [
    "839523066739949629"
  ],
  "logChannels": [
    "839523066739949629"
  ],
  "webhook": {
    "url": "",
    "mentions": {
      "everyone": false,
      "roles": false,
      "users": false
    }
  },
  "ignoreBots": true,
  "activityUpdateInterval": 120,
  "minecraftToDiscord": {
    "general": {
      "enableDebugLogs": false
    },
    "chatChannels": {
      "commandPrefix": "mc",
      "allowDiscordCommands": false,
      "serverStartingMessage": false,
      "serverStartMessage": true,
      "serverStopMessage": false,
      "serverStoppingMessage": true,
      "customChannelDescription": false,
      "minecraftToDiscordTag": false,
      "minecraftToDiscordDiscriminator": false,
      "playerMessages": false,
      "teamPlayerMessages": false,
      "joinAndLeaveMessages": true,
      "advancementMessages": false,
      "challengeMessages": false,
      "goalMessages": false,
      "deathMessages": false,
      "sendMeCommand": false,
      "sendSayCommand": false,
      "adminMessages": false,
      "atATellRaw": false,
      "achievementMessages": false
    },
    "logChannels": {
      "serverStartingMessage": false,
      "serverStartMessage": true,
      "serverStopMessage": false,
      "serverStoppingMessage": true,
      "customChannelDescription": false,
      "minecraftToDiscordTag": false,
      "minecraftToDiscordDiscriminator": false,
      "playerMessages": false,
      "teamPlayerMessages": false,
      "joinAndLeaveMessages": true,
      "advancementMessages": false,
      "challengeMessages": false,
      "goalMessages": false,
      "deathMessages": false,
      "sendMeCommand": false,
      "sendSayCommand": false,
      "adminMessages": false,
      "atATellRaw": false,
      "achievementMessages": false
    }
  },
  "discordToMinecraft": {
    "pingLongVersion": false
  },
  "emojiMap": [
    {
      "name": "example_name",
      "id": ":example_id:22222222"
    },
    {
      "name": "example_name2",
      "id": ":example_id2:22222222"
    }
  ],
  "version": 9
}
```

**Comment by thecatcore** [comment] 2021-08-14 13:10
Duplicate of #158

**Closed as completed by thecatcore** 2021-08-14 13:10 UTC
Labels: bug
